In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [4]:
arr1 = np.array((1, 2, 3, 4, 5))
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
arr2 = np.array(42)
print(arr2)

42


In [6]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
x = np.array([1,2,3,4,5]) 
np.save('outfile',x)
y = np.load('outfile.npy') 
print(y)

[1 2 3 4 5]


In [9]:
p = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',p) 
q = np.loadtxt('out.txt') 
print(q)

[1. 2. 3. 4. 5.]


In [10]:
arrr=np.arange(1,10,2) 
print("Elements of array: ",arrr)
arrr1=arrr[np.array([4,0,2,-1,-2])]
print("Indexed Elements of array arr: ",arrr1)

Elements of array:  [1 3 5 7 9]
Indexed Elements of array arr:  [9 1 5 9 7]


In [11]:
ar=np.arange(4)
print("Array ar:",ar)
print("Element at index 0 of ar is: ", ar[0])
print("Element at index 1 of ar is: ", ar[1])

Array ar: [0 1 2 3]
Element at index 0 of ar is:  0
Element at index 1 of ar is:  1


In [12]:
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("Element at eth row and eth column of arr1 is:",arr1[0,0]) 
print("Element at 1st row and 2nd column of arr1 is:", arr1[1,2])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at eth row and eth column of arr1 is: 0
Element at 1st row and 2nd column of arr1 is: 6


In [13]:
arr=np.arange(12) 
arr1=arr.reshape(2,2,3) 
print("Array arr1:\n", arr1) 
print("Element:", arr1[0,0,2])

Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element: 2


In [14]:
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1: \n",arr1)
print("\n")
print("elements of 1st row and 1st column upto last column \n", arr1[1:,1:4])

Array arr1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


elements of 1st row and 1st column upto last column 
 [[ 5  6  7]
 [ 9 10 11]]


In [15]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print('First array:') 
print(a) 
print('\n')  
   
print('Second array:') 
print(b) 
print('\n')  
   
print('First Array + Second Array' )
print( a + b)


First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [21]:
arr = np.arange(0,10)
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])